# Generated by Django 6.0.3 on 2026-03-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalflow',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Draft', 'Draft'), ('Closed/Skipped', 'Closed/Skipped')], default='Pending', max_length=20),
        ),
    ]
